name: Hello World

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup 4D
      run: |
        curl {{ secret.TOOL_URL }} --output 4d.zip
        unzip 4d.zip
        echo "{{ secret.LICENSE_4D }}" > $HOME/Application\ Support/4D/Licenses/"{{ secret.LICENSE_NAME }}".license4D
    - name: Run
      run: {{ secret.APP_PATH }} {{secret.OPTIONS}} "Project/TestLogOutput.4DProject"

