name: Hello World

on:
  push:
    paths:
    - 'Project/**'
    - '.github/workflows/hello.yml'

jobs:
  hello:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup 4D
      run: |
        curl ${{ secrets.TOOL_URL }} --output 4d.zip
        unzip -q 4d.zip
        mkdir -p $HOME/Application\ Support/4D/Licenses/
        echo "${{ secrets.LICENSE_4D }}" > $HOME/Application\ Support/4D/Licenses/"${{ secrets.LICENSE_NAME }}".license4D
    - name: Run
      timeout-minutes: 1
      run: |
        ${{ secrets.APP_PATH }} ${{ secrets.OPTIONS}} "Project/TestLogOutput.4DProject"

