name: Hello World

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup 4D
      run: |
        curl ${{ secrets.TOOL_URL }} --output 4d.zip
        unzip 4d.zip
        echo "${{ secrets.LICENSE_4D }}" > $HOME/Application\ Support/4D/Licenses/"${{ secrets.LICENSE_NAME }}".license4D
    - name: Run
      run: |
        ${{ secrets.APP_PATH }} ${{ secrets.OPTIONS}} "Project/TestLogOutput.4DProject"

